/*
 * DrawingPanel.java
 *
 * Created on 20 march 2005, 08:32
 *
 * Copyright (C) 2005  Marcin 'golish' Goliszewski <golish@niente.eu.org>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307,
 * USA.
 */

package netboard;

/**
 * A derivative of <CODE>javax.swing.JPanel</CODE> implementing drawing board capabilities
 * @author <a href="mailto:golish@niente.eu.org">Marcin 'golish' Goliszewski</a>
 */
public class DrawingPanel extends javax.swing.JPanel {
    
    /** Creates new DrawingPanel form */
    public DrawingPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);

        setBackground(java.awt.Color.white);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

    }
    // </editor-fold>//GEN-END:initComponents
    
    protected void paintComponent(java.awt.Graphics g) {
        if (drawing == null)
            initDrawing();
        
        g.drawImage(drawing, 0, 0, this);
    }
    
    /**
     * Initializes the drawing
     * @see netboard.DrawingPanel#drawing
     */
    private void initDrawing() {
        drawing = new java.awt.image.BufferedImage(getWidth(), getHeight(), java.awt.image.BufferedImage.TYPE_INT_ARGB);
        java.awt.Graphics2D graphics = drawing.createGraphics();
        graphics.setBackground(new java.awt.Color(1.0f, 1.0f, 1.0f, 0.0f));
        graphics.clearRect(0, 0, getWidth(), getHeight());
        graphics.dispose();
    }
    
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        java.awt.Graphics2D graphics = drawing.createGraphics();
        graphics.setColor(currentColor);
        
        if (currentTool.equals("Pen")) {
            graphics.drawLine(evt.getX(), evt.getY(), evt.getX(), evt.getY());
            resetCoords();
        } else if (currentTool.equals("Line")) {
            if (lastX < 0 || lastY < 0) {
                lastX = evt.getX();
                lastY = evt.getY();
                return;
            }
            
            graphics.drawLine(evt.getX(), evt.getY(), lastX, lastY);
            lastX = evt.getX();
            lastY = evt.getY();
        } else if (currentTool.equals("Circle")) {
            if (lastX < 0 || lastY < 0) {
                lastX = evt.getX();
                lastY = evt.getY();
                return;
            }
            
            int x = (evt.getX() - lastX > 0) ? lastX : evt.getX();
            int y = (evt.getY() - lastY > 0) ? lastY : evt.getY();
            
            graphics.fillOval(x, y, Math.abs(evt.getX() - lastX), Math.abs(evt.getY() - lastY));
            resetCoords();
        } else if (currentTool.equals("Rectangle")) {
            if (lastX < 0 || lastY < 0) {
                lastX = evt.getX();
                lastY = evt.getY();
                return;
            }
            
            int x = (evt.getX() - lastX > 0) ? lastX : evt.getX();
            int y = (evt.getY() - lastY > 0) ? lastY : evt.getY();
            
            graphics.fillRect(x, y, Math.abs(evt.getX() - lastX), Math.abs(evt.getY() - lastY));
            resetCoords();
        } else if (currentTool.equals("Ereaser")) {
            if (lastX < 0 || lastY < 0) {
                lastX = evt.getX();
                lastY = evt.getY();
                return;
            }
            
            graphics.setColor(graphics.getBackground());
            graphics.fillRect(evt.getX(), evt.getY(), 25, 25);
            lastX = evt.getX();
            lastY = evt.getY();
        }
        
        graphics.dispose();
        repaint();
    }//GEN-LAST:event_formMouseClicked
    
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        java.awt.Graphics2D graphics = drawing.createGraphics();
        graphics.setColor(currentColor);
        
        if (currentTool.equals("Pen")) {
            if (lastX < 0 || lastY < 0) {
                lastX = evt.getX();
                lastY = evt.getY();
                return;
            }
            
            graphics.drawLine(lastX, lastY, evt.getX(), evt.getY());
            lastX = evt.getX();
            lastY = evt.getY();
        } else if (currentTool.equals("Ereaser")) {
            if (lastX < 0 || lastY < 0) {
                lastX = evt.getX();
                lastY = evt.getY();
                return;
            }
            
            graphics.setColor(graphics.getBackground());
            graphics.fillRect(evt.getX(), evt.getY(), 25, 25);
            lastX = evt.getX();
            lastY = evt.getY();
        }
        
        graphics.dispose();
        repaint();
    }//GEN-LAST:event_formMouseDragged
    
    /**
     * Sets the current tool used to draw on the panel
     * @param tool Tool to set the drawing tool to
     */
    public void setCurrentTool(String tool) {
        currentTool = tool;
    }
    
    /**
     * Returns the current color used to draw on the panel
     * @return Current drawing color
     */
    public java.awt.Color getCurrentColor() {
        return currentColor;
    }
    
    /**
     * Sets the current color used to draw on the panel
     * @param color Color to set the current drawing color to
     */
    public void setCurrentColor(java.awt.Color color) {
        currentColor = color;
    }
    
    /**
     * Resets the saved coordinates (<CODE>lastX</CODE> and <CODE>lastY</CODE>) to <CODE>-1</CODE> (i.e. invalidates them)
     */
    public void resetCoords() {
        lastX = lastY = -1;
    }
    
    /**
     * Returns the image from the panel
     * @return Image from the panel
     */
    public java.awt.image.BufferedImage getImage() {
        return drawing;
    }
    
    /**
     * Sets the image on the panel
     * @param image New image to be shown on the panel
     */
    public void setImage(java.awt.image.BufferedImage image) {
        java.awt.Graphics2D graphics = drawing.createGraphics();
        graphics.drawImage(image, 0, 0, null);
        graphics.dispose();
        repaint();
    }
    
    public void clearImage() {
        drawing = null;
        repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    // My variables declaration
    /**
     * Current drawing tool
     */
    private String currentTool = "Pen";
    /**
     * Current drawing color
     */
    private java.awt.Color currentColor = java.awt.Color.black;
    /**
     * Current drawing
     */
    private java.awt.image.BufferedImage drawing = null;
    /**
     * Last used X coordinate; valid if greater than <CODE>0</CODE>
     */
    private int lastX = -1;
    /**
     * Last used Y coordinate; valid if greater than <CODE>0</CODE>
     */
    private int lastY = -1;
    // End of my variables declaration
}